name: Lint for accessibility issues

on:
  pull_request:
    paths:
      - 'client/src/**'
  workflow_dispatch:
    inputs:
      run_workflow:
        description: 'Set to true to run this workflow'
        required: true
        default: 'false'

jobs:
  axe-linter:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'danny-avila/LibreChat') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run_workflow == 'true')
    
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: dequelabs/axe-linter-action@70172799b6e61c64ba865c186348f39fa7ebc95d # v1
        with:
          api_key: ${{ secrets.AXE_LINTER_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
