name: Frontend Unit Tests

on:
  pull_request:
    branches: 
      - main
      - dev
      - dev-staging
      - release/*
    paths:
      - 'client/**'
      - 'packages/data-provider/**'

permissions:
  contents: read

jobs:
  tests_frontend_ubuntu:
    name: Run frontend unit tests on Ubuntu
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=${{ secrets.NODE_MAX_OLD_SPACE_SIZE || 6144 }}'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Use Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Client
        run: npm run frontend:ci

      - name: Run unit tests
        run: npm run test:ci --verbose
        working-directory: client

  tests_frontend_windows:
    name: Run frontend unit tests on Windows
    timeout-minutes: 60
    runs-on: windows-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=${{ secrets.NODE_MAX_OLD_SPACE_SIZE || 6144 }}'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Use Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Client
        run: npm run frontend:ci

      - name: Run unit tests
        run: npm run test:ci --verbose
        working-directory: client